"""json field in Portfolio

Revision ID: 04a0b978a8ff
Revises: 22235c9e034d
Create Date: 2019-12-17 20:37:51.323337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a0b978a8ff' # pragma: allowlist secret
down_revision = '22235c9e034d' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('csp_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'csp_data')
    # ### end Alembic commands ###
