"""recreate mutable json csp data field in Portfolio

Revision ID: 04af62b1790e
Revises: 02c3e3d359b8
Create Date: 2019-12-28 08:10:10.953241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04af62b1790e' # pragma: allowlist secret
down_revision = '02c3e3d359b8' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'csp_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('csp_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
