"""create state machine state enum field

Revision ID: 0faa07de4a61
Revises: 9a2c7d10ba8d
Create Date: 2019-12-27 14:36:06.572089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0faa07de4a61' # pragma: allowlist secret
down_revision = '9a2c7d10ba8d' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_state_machines', sa.Column('state', sa.Enum('UNSTARTED', 'STARTING', 'STARTED', 'COMPLETED', 'FAILED', 'TENANT_CREATED', 'TENANT_CREATION_IN_PROGRESS', 'TENANT_CREATION_FAILED', name='fsmstates', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_state_machines', 'state')
    # ### end Alembic commands ###
