"""portfolio provision. extend FSMStates enum

Revision ID: 123b34b2a876
Revises: 5842a3fd16cd
Create Date: 2019-12-30 11:16:05.700678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '123b34b2a876' # pragma: allowlist secret
down_revision = '5842a3fd16cd' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_state_machines', sa.Column('state', sa.Enum('UNSTARTED', 'STARTING', 'STARTED', 'COMPLETED', 'FAILED', 'TENANT_CREATED', 'TENANT_CREATION_IN_PROGRESS', 'TENANT_CREATION_FAILED', 'BILLING_PROFILE_CREATED', 'BILLING_PROFILE_CREATION_IN_PROGRESS', 'BILLING_PROFILE_CREATION_FAILED', 'BILLING_PROFILE_UPDATED', 'BILLING_PROFILE_UPDATE_IN_PROGRESS', 'BILLING_PROFILE_UPDATE_FAILED', 'ADMIN_SUBSCRIPTION_CREATED', 'ADMIN_SUBSCRIPTION_CREATION_IN_PROGRESS', 'ADMIN_SUBSCRIPTION_CREATION_FAILED', name='fsmstates', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_state_machines', 'state')
    # ### end Alembic commands ###
