"""recreate portfolio csp data json field. create mutable dict

Revision ID: 1574ffa5c0c6
Revises: 5c12ce76620a
Create Date: 2019-12-27 16:11:20.168258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1574ffa5c0c6' # pragma: allowlist secret
down_revision = '5c12ce76620a' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('csp_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'csp_data')
    # ### end Alembic commands ###
