"""portfolio state machine add state field. 

Revision ID: 22235c9e034d
Revises: 54e22bdf14b3
Create Date: 2019-12-17 16:38:54.007851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22235c9e034d' # pragma: allowlist secret
down_revision = '54e22bdf14b3' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_state_machines', sa.Column('state', sa.Enum('UNSTARTED', 'STARTING', 'STARTED', 'COMPLETED', 'FAILED', name='fsmstate', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_state_machines', 'state')
    # ### end Alembic commands ###
