"""recreate jsonb csp data field in Portfolio

Revision ID: 43c529f2c4fb
Revises: 1574ffa5c0c6
Create Date: 2019-12-27 18:28:31.011820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43c529f2c4fb' # pragma: allowlist secret
down_revision = '1574ffa5c0c6' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'csp_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('csp_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
