"""use sqlalchemy-json lib to create mutable json csp data field in Portfolio

Revision ID: 6a0fcfdddb38
Revises: 04af62b1790e
Create Date: 2019-12-28 08:29:50.270512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import sqlalchemy_json

# revision identifiers, used by Alembic.
revision = '6a0fcfdddb38' # pragma: allowlist secret
down_revision = '04af62b1790e' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('csp_data', sqlalchemy_json.NestedMutableJson(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'csp_data')
    # ### end Alembic commands ###
