"""recreate state machine state enum

Revision ID: 9a2c7d10ba8d
Revises: 735e7528b723
Create Date: 2019-12-27 14:17:37.302299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a2c7d10ba8d' # pragma: allowlist secret
down_revision = '735e7528b723' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_state_machines', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_state_machines', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
