"""remove machine_instance field from portfolio state machine

Revision ID: aeb23316f068
Revises: 04a0b978a8ff
Create Date: 2019-12-18 14:56:33.952474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aeb23316f068' # pragma: allowlist secret
down_revision = '04a0b978a8ff' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_state_machines', 'machine_instance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_state_machines', sa.Column('machine_instance', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
